"""add_full_name_and_verified_to_users

Revision ID: 8a75110865d7
Revises: 9c7bb6e6ce19
Create Date: 2026-04-19 15:17:55.347799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a75110865d7'
down_revision: Union[str, None] = '9c7bb6e6ce19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_otp_email_purpose', table_name='otp_codes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_otp_email_purpose', 'otp_codes', ['email', 'purpose'], unique=False)
    # ### end Alembic commands ###
