web: alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000} --proxy-headers --forwarded-allow-ips="*" --workers ${WEB_CONCURRENCY:-2}
worker: celery -A celery_worker.celery_app worker --loglevel=info -Q default --concurrency=${CELERY_CONCURRENCY:-2}
beat: celery -A celery_worker.celery_app beat --loglevel=info
