"""Measure a symbol-attribution matcher before committing to one.

Run: PYTHONIOENCODING=utf-8 python -m scratch.probe_symbol_match

I-08 has to attribute each scraped article to the CSE symbols it is about. Three
approaches fail, each measured here rather than reasoned about:

  1. substring ticker search -- "ACL" is inside "MIRACLE", "AEL" inside "FUEL",
     and all 273 base tickers are 3-4 alphabetic characters, so a plain
     ``if base in text`` attributes half the market to every article;
  2. exact filed-name search -- cse.lk files "SOFTLOGIC LIFE INSURANCE PLC" while
     a headline says "Softlogic Life", so requiring the filed name matches almost
     nothing;
  3. blind N-token prefixes of the filed name -- this was the first thing tried
     here and it attributed "Sri Lanka's digital commerce landscape is growing:
     Visa" to SLTL, because "SRI LANKA TELECOM PLC" yields the prefix "sri lanka"
     and virtually every headline on these three sites contains it.

What survives measurement: prefixes generated by stripping *industry* tails
rather than by token count, with any phrase made entirely of geographic or
generic corporate words discarded, plus longest-match-wins so an ambiguous short
phrase does not add a second company when a longer phrase already named one.
"""
import re
from collections import Counter

from app.database import SessionLocal
from app.models.stock import CompanyInfo, NewsSentiment

# Trailing words that are legal form rather than identity.
LEGAL_TAIL = {"plc", "ltd", "limited", "company", "co", "corporation", "corp",
              "inc", "pvt", "private"}

# Trailing words that say what the company does, not which company it is. Peeled
# one at a time to derive how a headline would actually name it: "SOFTLOGIC LIFE
# INSURANCE" -> "softlogic life".
INDUSTRY_TAIL = {
    "insurance", "assurance", "finance", "financial", "bank", "banking",
    "holdings", "holding", "plantations", "plantation", "hotels", "hotel",
    "resorts", "resort", "industries", "industry", "industrial", "developments",
    "development", "investments", "investment", "capital", "group", "telecom",
    "telecommunications", "power", "energy", "cables", "mills", "foods", "food",
    "beverages", "beverage", "textiles", "leisure", "properties", "property",
    "estates", "estate", "breweries", "brewery", "distilleries", "motors",
    "trading", "traders", "services", "service", "tea", "lands", "land",
    "chemicals", "packaging", "printing", "logistics", "shipping", "marine",
    "electricals", "electrical", "electronics", "constructions", "construction",
    "engineering", "systems", "technologies", "technology", "solutions",
    "international", "exports", "imports", "agencies", "enterprises", "ventures",
    "assets", "asset", "funds", "fund", "trust", "trusts", "securities", "life",
}

# Words that identify a place or say nothing. A phrase made only of these is not
# an identification -- "sri lanka", "asian", "national", "ceylon".
GENERIC = {
    "sri", "lanka", "lankan", "ceylon", "colombo", "asia", "asian", "national",
    "people", "s", "central", "united", "first", "new", "royal", "union",
    "eastern", "western", "southern", "northern", "global", "general",
    "standard", "premier", "prime", "grand", "commercial", "and", "the", "of",
    "co", "pan", "east", "west", "north", "south",
}

# A one-word identification has to be at least this long. 4 rather than 5 so
# "ODEL PLC" -> "odel" is usable; below that a name is too short to distinguish
# from an abbreviation in prose.
MIN_SOLO_TOKEN = 4

# Derived short forms are peeled down to at least this many tokens. Stopping at 2
# is what keeps "SANASA DEVELOPMENT BANK" from yielding bare "sanasa", which
# attributed a Sanasa Life Insurance story to Sanasa Development Bank -- a
# different listed entity sharing a group brand. Genuinely one-word companies
# (Hayleys, Hemas, Agstar, Odel) are unaffected: their single token is the *full*
# filed name, which is admitted by a separate rule.
MIN_DERIVED_TOKENS = 2


def toks(text: str) -> list[str]:
    """Lowercase alphanumeric tokens. Token lists, not substrings, so 'acl'
    cannot match inside 'miracle'."""
    return re.findall(r"[a-z0-9]+", (text or "").lower())


def name_phrases(name: str) -> list[list[str]]:
    """Token sequences that identify this company in running text, longest first.

    Two rules, and the split between them is the whole design. An earlier version
    applied one test to both and silently produced *no phrase at all* for 25
    companies including UNION ASSURANCE, NATIONAL DEVELOPMENT BANK, PEOPLE'S
    INSURANCE and UNION BANK OF COLOMBO -- every token of those names is generic
    or an industry word in isolation, so a blanket "reject all-generic phrases"
    test threw away the filed name itself.

    1. The **full filed name** minus legal suffix is always an identification.
       "union bank of colombo" is specific as a contiguous four-token phrase no
       matter how unremarkable each word is alone.
    2. **Derived short forms** -- the full name with industry/place tails peeled
       off, which is how a headline actually refers to a company -- are where the
       false positives live, so they carry both extra tests: at least two tokens,
       and not made *entirely* of GENERIC placeholders. That second test is what
       stops "SRI LANKA TELECOM" from yielding "sri lanka" and attributing every
       story on these three sites to SLTL. Note it tests GENERIC only, not
       GENERIC|INDUSTRY_TAIL: "union bank" and "asian hotels" are real short
       forms and survive, "sri lanka" and "people s" do not.
    """
    t = toks(name)
    while t and t[-1] in LEGAL_TAIL:
        t.pop()
    if not t:
        return []

    out: list[list[str]] = []
    if len(t) >= 2 or len(t[0]) >= MIN_SOLO_TOKEN:
        out.append(list(t))

    cur = list(t)
    while len(cur) > MIN_DERIVED_TOKENS and cur[-1] in (INDUSTRY_TAIL | GENERIC):
        cur.pop()
        if not all(tok in GENERIC for tok in cur) and cur not in out:
            out.append(list(cur))
    return out


def contains(hay: list[str], needle: list[str]) -> bool:
    n = len(needle)
    return any(hay[i:i + n] == needle for i in range(len(hay) - n + 1))


def build(db):
    phrases: dict[str, list[list[str]]] = {}
    by_base: dict[str, list[str]] = {}
    for sym, name in db.query(CompanyInfo.symbol, CompanyInfo.name).all():
        p = name_phrases(name or "")
        if p:
            phrases[sym] = p
        by_base.setdefault(sym.split(".")[0].upper(), []).append(sym)
    return phrases, by_base


TICKER_RE = re.compile(r"\b[A-Z][A-Z0-9]{2,5}\b")

# Base tickers that must never be matched as tickers because the same letters are
# ordinary text in financial news. PLC is the one that mattered in measurement:
# "PEOPLE'S LEASING & FINANCE PLC" trades as PLC.N0000, and "PLC" is the legal
# suffix of almost every Sri Lankan listed company -- so a bare ticker match
# attributed "Assetline Finance PLC marks transformational year" to People's
# Leasing. Of the three base tickers that appeared as capitalised tokens across
# the 60 stored headlines (CDB, NTB, PLC), that was the only false one, and this
# turns 2-of-3 into 2-of-2.
#
# The rest are pre-emptive: acronyms that recur constantly on these three sites.
# Blocking a ticker only costs recall when a story names the company by ticker
# alone, and the company name path still catches those.
TICKER_BLOCKLIST = {
    "PLC", "LTD", "INC", "CO",
    "CSE", "ASPI", "CBSL", "SEC", "GDP", "CPI", "VAT", "PAYE", "IPO", "ETF",
    "NAV", "EPS", "AGM", "EGM", "ESG", "IFRS", "SLFRS", "GAAP",
    "CEO", "CFO", "COO", "CIO", "CTO", "MD", "HR", "PR", "IT", "AI", "API",
    "USD", "LKR", "EUR", "GBP", "INR", "SME", "SMB", "FDI", "FMCG",
    "IMF", "ADB", "WB", "UN", "EU", "UK", "US", "USA", "SL", "TV", "ATM",
}


def attribute(text: str, phrases, by_base):
    hay = toks(text)
    # symbol -> (matched phrase, how)
    raw: dict[str, tuple[list[str], str]] = {}
    for sym, plist in phrases.items():
        for p in plist:                       # longest first
            if contains(hay, p):
                raw[sym] = (p, "name:" + " ".join(p))
                break

    # Longest match wins: if one company was identified by "softlogic life
    # insurance", drop a different company matched only by "softlogic".
    best = max((len(p) for p, _ in raw.values()), default=0)
    drop = set()
    for sym, (p, _) in raw.items():
        for sym2, (p2, _) in raw.items():
            if sym2 != sym and len(p2) > len(p) and contains(p2, p):
                drop.add(sym)
    hits = {s: h for s, (p, h) in raw.items() if s not in drop}

    letters = [c for c in text if c.isalpha()]
    shouty = bool(letters) and sum(c.isupper() for c in letters) / len(letters) > 0.6
    if not shouty:
        for m in TICKER_RE.finditer(text):
            if m.group(0) in TICKER_BLOCKLIST:
                continue
            for sym in by_base.get(m.group(0), []):
                hits.setdefault(sym, "ticker:" + m.group(0))
    return hits


def main():
    db = SessionLocal()
    phrases, by_base = build(db)
    print(f"{len(phrases)} of 293 companies have usable name phrases; "
          f"{len(by_base)} base tickers")
    nophrase = [s for s, n in db.query(CompanyInfo.symbol, CompanyInfo.name).all()
                if s not in phrases]
    print(f"no usable phrase ({len(nophrase)}): {nophrase[:12]}")

    # Which phrases are shared by more than one company?
    seen = Counter()
    for plist in phrases.values():
        for p in plist:
            seen[" ".join(p)] += 1
    amb = [k for k, v in seen.items() if v > 1]
    print(f"ambiguous phrases ({len(amb)}): {sorted(amb)[:14]}")

    rows = db.query(NewsSentiment.headline, NewsSentiment.source).all()
    print(f"\n=== attributing {len(rows)} stored headlines (headline only) ===")
    nmatched = 0
    per_sym = Counter()
    for headline, src in rows:
        hits = attribute(headline, phrases, by_base)
        if hits:
            nmatched += 1
            per_sym.update(hits.keys())
            host = (src or "").split("/")[2][:16] if "//" in (src or "") else "?"
            print(f"  [{host:<16}] {headline[:56]}")
            for sym, how in sorted(hits.items()):
                print(f"        -> {sym:<12} {how}")
    print(f"\n{nmatched}/{len(rows)} headlines attributed; "
          f"top symbols: {per_sym.most_common(6)}")

    print("\n=== unmatched (should be genuinely company-free) ===")
    for headline, _ in rows:
        if not attribute(headline, phrases, by_base):
            print(f"  {headline[:86]}")
    db.close()


if __name__ == "__main__":
    main()
